services:
  dockdns:
    container_name: dyndns
    image: ghcr.io/tarow/dockdns:v0.8.1
    restart: unless-stopped
    volumes:
      - ./config.enc.yaml:/app/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
