volumes:
  caddy_data:
  caddy_config:

networks:
  proxy:
    name: proxy

services:
  vaultls:
    container_name: vaultls
    image: ghcr.io/7ritn/vaultls:v0.11.0
    restart: unless-stopped
    volumes:
      - /srv/vaultls/:/app/data/
    networks:
      - proxy
    env_file:
      - secrets.enc.env
  caddy:
    container_name: caddy
    image: ghcr.io/caddybuilds/caddy-cloudflare:2.10.2-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./vaultls/:/vaultls/
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy
    env_file:
      - secrets.enc.env
