---
- name: Create doco-cd compose directory
  ansible.builtin.file:
    path: /opt/doco-cd
    state: directory
    mode: "0755"
  tags:
    - setup

- name: Setup compose.yml
  ansible.builtin.template:
    src: compose.j2
    dest: /opt/doco-cd/compose.yml
    mode: "0644"
  tags:
    - setup
    - update

- name: Create and start doco-cd
  community.docker.docker_compose_v2:
    project_src: /opt/doco-cd
  tags:
    - setup
    - update
