networks:
  dns:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/24
  proxy:
    external: true

services:
  unbound:
    container_name: unbound
    image: madnuttah/unbound:1.23.1-2
    restart: unless-stopped
    hostname: unbound
    environment:
      TZ: Europe/Berlin
      UNBOUND_UID: "1000"
      UNBOUND_GID: "1000"
    networks:
      dns:
        ipv4_address: 10.2.0.200

  pihole:
    container_name: pihole
    image: pihole/pihole:2025.11.1
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      TZ: Europe/Berlin
      FTLCONF_dns_listeningMode: all
      FTLCONF_dns_upstreams: 10.2.0.200#5335
    volumes:
      - /srv/pihole:/etc/pihole/
      - /srv/dnsmasq:/etc/dnsmasq.d/
    env_file:
      - secrets.enc.env
    cap_add:
      - NET_ADMIN
    networks:
      - dns
      - proxy