---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/
    - Gentoo Wiki:
        - abbr: GW
          href: https://wiki.gentoo.org/
    - Gentoo Devmanual:
        - abbr: GM
          href: https://devmanual.gentoo.org/

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/