networks:
  proxy:
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.10.1
    container_name: homepage
    volumes:
      - ./settings.yaml:/app/config/settings.yaml
      - ./bookmarks.yaml:/app/config/bookmarks.yaml
      - ./services.yaml:/app/config/services.yaml
      - ./widgets.yaml:/app/config/widgets.yaml
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.tmak2002.de
    networks:
      - proxy
    labels:
      - dockdns.name=home.tmak2002.de
      - dockdns.proxied=false