networks:
  proxy:
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.10.1
    container_name: homepage
    volumes:
      - /srv/homepage/:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.tmak2002.de
    networks:
      - proxy
    labels:
      - dockdns.name=home.tmak2002.de
      - dockdns.proxied=false