---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: custom
    url: https://search.catsarebeautiful.de/search?q=
    target: _blank